Shop.Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Interfaces;
using Shop.Domain.Models.Account;
using Shop.Domain.ViewModels.Admin.Products;
using Shop.Domain.ViewModels.Site.Products;
using Shop.Web.Extentions;
using System.Threading.Tasks;

namespace Shop.Web.Controllers
{
    public class ProductController : SiteBaseController
    {
        #region constractor
        private readonly IProductService _productService;
        private readonly IOrderService _orderService;
        public ProductController(IProductService productService, IOrderService orderService)
        {
            _productService = productService;
            _orderService = orderService;
        }
        #endregion


        #region products
        [HttpGet("products")]
        public async Task<IActionResult> Products(FilterProductsViewModel filter)
        {
            filter.TakeEntity = 12;
            filter.ProductBox = ProductBox.ItemBoxInSite;

            ViewData["Categories"] = await _productService.GetAllProductCategories();
            return View(await _productService.FilterProducts(filter));
        }
        #endregion

        #region show-product
        [HttpGet("showDetail/{productId}")]
        public async Task<IActionResult> ProductDetail(long productId)
        {
            var data = await _productService.ShowProductDetail(productId);
            if (data == null)
            {
                return NotFound();
            }


            TempData["relatedProduct"] = await _productService.GetRelatedProduct(data.ProductCategory.UrlName, productId);
            return View(data);
        }
        #endregion

        #region create-product-comment
        [HttpPost("add-comment"), ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProductComment(CreateProductCommentViewModel createProductComment)
        {
            if (!string.IsNullOrEmpty(createProductComment.Text))
            {
                var result = await _productService.CreateProductComment(createProductComment, User.GetUserId());
                switch (result)
                {
                    case CreateProductCommentResult.CheckUser:
                        TempData[WarningMessage] = "کاربر مورد نظر یافت نشد";
                        break;
                    case CreateProductCommentResult.CheckProduct:
                        TempData[WarningMessage] = "محصولی یافت نشد";
                        break;
                    case CreateProductCommentResult.Suucess:
                        TempData[SuccessMessage] = "نظر شما با موفقیت ثبت شد";
                        return RedirectToAction("ProductDetail", new { productId = createProductComment.ProductId });

                }
            }

            TempData[ErrorMessage] = "لطفا نظر خود را وارد نمایید";
            return RedirectToAction("ProductDetail", new { productId = createProductComment.ProductId });

        }
        #endregion

        #region buy-product

        [Authorize]
        public async Task<IActionResult> BuyProduct(long productId)
        {
            long orderId = await _orderService.AddOrder(User.GetUserId(), productId);
            return Redirect("/User/Basket/" + orderId);
        }
        #endregion
    }
}

Shop.Web/ViewComponets/SiteViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Interfaces;
using Shop.Domain.ViewModels.Admin.Products;
using Shop.Domain.ViewModels.Site.Sliders;
using Shop.Web.Extentions;
using System.Threading.Tasks;

namespace Shop.Web.ViewComponets
{
    #region site header
    public class SiteHeaderViewComponent(IUserService userService, IOrderService orderService) : ViewComponent
    {
        private readonly IUserService _userService = userService;
        private readonly IOrderService _orderService = orderService;

        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (User.Identity!.IsAuthenticated)
            {
                ViewBag.User = await _userService.GetUserByPhoneNumber(User.Identity.Name);
                ViewBag.Order = await _orderService.GetUserBasket(User.GetUserId());
                ViewBag.UserCompare = await _userService.GetUserCompares(User.GetUserId());
                ViewBag.FavoriteCount = await _userService.UserFavoriteCount(User.GetUserId());
            }
            return View("SiteHeader");
        }
    }
    #endregion

    #region site footer
    public class SiteFooterViewComponent : ViewComponent
    {
        public IViewComponentResult InvokeAsync()
        {
            return View("SiteFooter");
        }
    }
    #endregion

    #region slider - home
    public class SliderHomeViewComponent(ISiteSettingService siteSettingService) : ViewComponent
    {
        #region constractor
        private readonly ISiteSettingService _siteSettingService = siteSettingService;
        #endregion

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var filterSlidersViewModel = new FilterSlidersViewModel()
            {
                TakeEntity = 10
            };

            var data = await _siteSettingService.FilterSliders(filterSlidersViewModel);

            return View("SliderHome", data);
        }
    }
    #endregion

    #region popular category - home
    public class PopularCategoryViewComponent(IProductService productService) : ViewComponent
    {
        #region constractor
        private readonly IProductService _productService = productService;
        #endregion

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var filterCategory = new FilterProductCategoriesViewModel()
            {
                TakeEntity = 6
            };

            var data = await _productService.FilterProductCategories(filterCategory);

            return View("PopularCategory", data);
        }
    }
    #endregion

    #region popular category - home
    public class SideBarCategoryViewComponent(IProductService productService) : ViewComponent
    {
        #region constractor
        private readonly IProductService _productService = productService;
        #endregion

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var filterCategory = new FilterProductCategoriesViewModel();

            var data = await _productService.FilterProductCategories(filterCategory);

            return View("SideBarCategory", data);
        }
    }
    #endregion

    #region All-productInSlider - home
    public class AllProductInSliderViewComponent(IProductService productService) : ViewComponent
    {
        #region constractor
        private readonly IProductService _productService = productService;
        #endregion

        public async Task<IViewComponentResult> InvokeAsync()
        {

            var data = await _productService.ShowAllProductInSlider();

            return View("AllProductInSlider", data);
        }
    }
    #endregion

    #region All-productInCategoryPc - home
    public class AllInCategoryPcViewComponent(IProductService productService) : ViewComponent
    {
        #region constractor
        private readonly IProductService _productService = productService;
        #endregion

        public async Task<IViewComponentResult> InvokeAsync()
        {

            var data = await _productService.ShowAllProductInCategory("pc");

            return View("AllInCategoryPc", data);
        }
    }
    #endregion

    #region All-productInCategoryPc - home
    public class AllInCategoryTvViewComponent(IProductService productService) : ViewComponent
    {
        #region constractor
        private readonly IProductService _productService = productService;
        #endregion

        public async Task<IViewComponentResult> InvokeAsync()
        {

            var data = await _productService.ShowAllProductInCategory("tv");

            return View("AllInCategoryTv", data);
        }
    }
    #endregion

    #region All-productInCategoryPc - home
    public class ProductCommentsViewComponent(IProductService productService) : ViewComponent
    {
        #region constractor
        private readonly IProductService _productService = productService;
        #endregion

        public async Task<IViewComponentResult> InvokeAsync(long productId)
        {

            var data = await _productService.AllProductCommentById(productId);

            return View("ProductComments", data);
        }
    }
    #endregion
}

Shop.Web/Views/Shared/_CaptchaInput.cshtml
@model Shop.Domain.ViewModels.Site.Recaptcha

<input type="hidden" asp-for="Token" id="captchaInput" />  

Shop.Web/Views/Shared/_CaptchaScripts.cshtml
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration
<script src="https://www.google.com/recaptcha/api.js?render=@Configuration["googleReCaptcha:SiteKey"]"></script>
<script>
    grecaptcha.ready(function () {
        window.grecaptcha.execute('@Configuration["googleReCaptcha:SiteKey"]', { action: 'home' }).then(function (token) {
            $("#captchaInput").val(token);
        });
    });
</script>

Shop.Web/Views/Shared/_FooterRefrences.cshtml
 <!-- Plugins JS File -->
<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.bundle.min.js"></script>
<script src="/js/jquery.hoverIntent.min.js"></script>
<script src="/js/jquery.waypoints.min.js"></script>
<script src="/js/superfish.min.js"></script>
<script src="/js/owl.carousel.min.js"></script>
<script src="/js/bootstrap-input-spinner.js"></script>
<script src="/js/jquery.plugin.min.js"></script>
<script src="/js/jquery.magnific-popup.min.js"></script>
<script src="/js/jquery.countdown.min.js"></script>
<!-- Main JS File -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7/dist/sweetalert2.all.min.js"></script>
<script src="/js/main.js"></script>
<script src="/js/demos/demo-4.js"></script>
<script src="/js/notifications.js"></script>
<script src="/js/custom.js"></script>

Shop.Web/Views/Shared/_HeaderRefrences.cshtml
   <!-- Plugins CSS File -->
<link rel="stylesheet" href="/css/bootstrap.min.css">
<link rel="stylesheet" href="/css/bootstrap-rtl.min.css">
<link rel="stylesheet" href="/css/plugins/owl-carousel/owl.carousel.css">
<link rel="stylesheet" href="/css/plugins/magnific-popup/magnific-popup.css">
<link rel="stylesheet" href="/css/plugins/jquery.countdown.css">
<!-- Main CSS File -->
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/skins/skin-demo-4.css">
<link rel="stylesheet" href="/css/demos/demo-4.css">
<link rel="stylesheet" href="/vendor/line-awesome/line-awesome/line-awesome/css/line-awesome.min.css">
<link href="/css/notifications.css" rel="stylesheet" />
<link href="/userPanel/css/account.css" rel="stylesheet" />
<link href="/userPanel/css/style.css" rel="stylesheet" />

Shop.Web/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"]</title>

    <partial name="_TagRefrences" />
    <partial name="_HeaderRefrences" />
    @RenderSection("styles", false)
</head>

<body>
    <div class="page-wrapper">
        @await Component.InvokeAsync("SiteHeader")
        <main class="main">
            @RenderBody()
        </main>
        <!-- End .main -->
        @await Component.InvokeAsync("SiteFooter")
    </div>
    <button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>


    <partial name="_Mobile" />
    <partial name="_FooterRefrences" />
    @RenderSection("scripts", false)
    <partial name="_Message" />
</body>

</html>

Shop.Web/Views/Shared/_Message.cshtml
@if (TempData["SuccessMessage"] != null ||
TempData["WarningMessage"] != null ||
TempData["ErrorMessage"] != null ||
TempData["InfoMessage"] != null)
{
    @if (TempData["SuccessMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowMessage('پیغام موفقیت', '@TempData["SuccessMessage"]', 'success')
            });
        </script>
    }

    @if (TempData["WarningMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowMessage('پیغام اخطار', '@TempData["WarningMessage"]', 'warning')
            });
        </script>
    }

    @if (TempData["ErrorMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowMessage('پیغام خطا', '@TempData["ErrorMessage"]', 'error')
            });
        </script>
    }

    @if (TempData["InfoMessage"] != null)
    {
        <script>
            $(document).ready(function () {
                ShowMessage('پیغام اطالاعیه', '@TempData["InfoMessage"]', 'info')
            });
        </script>
    }
}

Shop.Web/Views/Shared/_NewProductBox.cshtml
@model List<Shop.Domain.ViewModels.Site.Products.ProductItemViewModel>

@if (Model != null && Model.Any())
{
    @foreach (var product in Model)
    {
        <div class="col-6 col-md-4 col-lg-3">
            <div class="product product-2">
                <figure class="product-media">
                    <span class="product-label label-circle label-sale">جدید</span>
                    <a asp-area="" asp-controller="Product" asp-action="ProductDetail" asp-route-productId="@product.ProductId">
                        <img src="@(PathExtensions.ProductOrgin +product.ProductImageName)" alt="@product.ProductName"
                             class="product-image" title="@product.ProductName">
                    </a>

                    <div class="product-action-vertical">
                        <a asp-area="User" asp-controller="Account" asp-action="AddUserFavorite" asp-route-productId="@product.ProductId" class="btn-product-icon btn-wishlist"
                           title="افزودن به لیست علاقه مندی"></a>
                    </div><!-- End .product-action -->

                    <div class="product-action">
                        <a asp-area="" asp-controller="Product" asp-action="BuyProduct" asp-route-productId="@product.ProductId" class="btn-product btn-cart" title="افزودن به سبد خرید">
                            <span>
                                افزودن
                                به
                                سبد خرید
                            </span>
                        </a>
                    </div>
                </figure>

                <div class="product-body">
                    <div class="product-cat">
                        <a asp-area="" asp-controller="Product" asp-action="Products" asp-route-FilterByCategory="@product.ProductCategory.UrlName">@product.ProductCategory.Title</a>
                    </div><!-- End .product-cat -->
                    <h3 class="product-title"><a asp-area="" asp-controller="Product" asp-action="ProductDetail" asp-route-productId="@product.ProductId">@product.ProductName</a></h3>
                    <!-- End .product-title -->
                    <div class="product-price">
                        <span class="new-price">@product.Price.ToString("#,0 تومان")</span>
                    </div><!-- End .product-price -->

                    <span class="ratings-text">( @product.CommentCount )</span>
                </div><!-- End .rating-container -->


            </div><!-- End .product-body -->
        </div>
    }
}

Shop.Web/Views/Shared/_Paging.cshtml
@model Shop.Domain.ViewModels.Paging.BasePaging



<div class="pagination-area">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center d-flex ">

            @if (Model.StartPage < Model.PageId)
            {

                <li class="page-item">
                    <a class="page-link" onclick="FillPageId(@(Model.PageId -1))" aria-label="Next">
                        <i class="icon-arrow-right"></i>
                    </a>
                </li>
            }

            @for (int i = Model.StartPage; i <= Model.EndPage; i++)
            {

                <li class="page-item @(Model.PageId ==i?"active":"")"><a class="page-link" onclick="FillPageId(@i)">@i</a></li>
            }



            @if (Model.EndPage > Model.PageId)
            {

                <li class="page-item">
                    <a class="page-link" onclick="FillPageId(@(Model.PageId +1))" aria-label="Previous">
                        <i class="icon-arrow-left"></i>
                    </a>
                </li>
            }
        </ul>
    </nav>
</div>

Shop.Web/Views/Shared/_ProductBox.cshtml
@model Shop.Domain.ViewModels.Site.Products.ProductItemViewModel

<div class="product product-2">
    <figure class="product-media">
        <a href="product.html">
            <img src="@(PathExtensions.ProductOrgin +Model.ProductImageName)" alt="تصویر محصول" class="product-image">
        </a>

        <div class="product-action-vertical">
            <a asp-area="User" asp-controller="Account" asp-action="AddUserFavorite" asp-route-productId="@Model.ProductId" class="btn-product-icon btn-wishlist" title="افزودن به لیست علاقه مندی"></a>
        </div><!-- End .product-action -->

        <div class="product-action">
            <a asp-controller="Product" asp-action="BuyProduct" asp-route-productId="@Model.ProductId" class="btn-product btn-cart" title="افزودن به سبد خرید">
                <span>
                    افزودن
                    به
                    سبد خرید
                </span>
            </a>
        </div><!-- End .product-action -->
    </figure><!-- End .product-media -->

    <div class="product-body">
        <div class="product-cat">
            <a asp-area="" asp-controller="Product" asp-action="Products" asp-route-FilterByCategory="@Model.ProductCategory.UrlName">@Model.ProductCategory.Title</a>
        </div><!-- End .product-cat -->
        <h3 class="product-title">
            <a asp-area="" asp-controller="Product" asp-action="ProductDetail" asp-route-productId="@Model.ProductId">
                @Model.ProductName
            </a>
        </h3><!-- End .product-title -->
        <div class="product-price">
            @Model.Price.ToString("#,0 تومان")
        </div><!-- End .product-price -->
        <div class="ratings-container">
            <div class="ratings">
                <div class="ratings-val" style="width: 80%;"></div><!-- End .ratings-val -->
            </div><!-- End .ratings -->
            <span class="ratings-text">@Model.CommentCount</span>
        </div><!-- End .rating-container -->
    </div><!-- End .product-body -->
</div>

Shop.Web/Views/Shared/_TagRefrences.cshtml
<meta name="keywords" content="HTML5 Template">
<meta name="description" content="Molla - Bootstrap eCommerce Template">
<meta name="author" content="p-themes">
<!-- Favicon -->
<link rel="apple-touch-icon" sizes="180x180" href="assets/images/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="assets/images/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="assets/images/icons/favicon-16x16.png">
<link rel="manifest" href="assets/images/icons/site.webmanifest">
<link rel="mask-icon" href="assets/images/icons/safari-pinned-tab.html" color="#666666">
<link rel="shortcut icon" href="assets/images/icons/favicon.ico">
<meta name="apple-mobile-web-app-title" content="Molla">
<meta name="application-name" content="Molla">
<meta name="msapplication-TileColor" content="#cc9966">
<meta name="msapplication-config" content="assets/images/icons/browserconfig.html">
<meta name="theme-color" content="#ffffff">

Shop.Web/Views/Shared/_ValidationScripts.cshtml
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>